### ISSUE TITLE
Revising Database

### ISSUE THREAD

**Issue by nrcardeal** [carolinacouto98/Queuality#12]
Employee:
* name : string
* id (sub) : string
* sections : array<string>
* roles : array<string>
* desk : string

Section:
* id : ObjectId
* name : string (unique)
* employees : array<string>
* working-hours : {
  * begin : string
  * end : string
  * duration : number
}
* queue : array<string>
* subjects : array {
  * name (id) : string
  * subject : string
  * priority : boolean
  * current-ticket : number
  * next-ticket : number
  * date : timestamp
  * desks: `array<string>`
}

Appointment:
* id : ObjectId
* subject : string
* desk : string
* date : timestamp
* section : string

**Comment by carolinacouto98** [comment]
Section:Subject: total-tickets
